import Head from 'next/head'
import Image from 'next/image'
//import styles from '../styles/Home.module.css'
import { BG_Finder2 } from '../components/BG-Finder-2'
import React, { useState, useEffect} from 'react';
import { BG_display } from '../components/BG-display';

export default function Home() {
  const [ID1, setID1] = useState('start')
  const [ID2, setID2] = useState('')

  function IDupdate (pos, ID) {
    if (pos === "1") {
      setID1(ID)
    } else if (pos === "2") {
      setID2(ID)
    }
  }

  return (
    <div className='app'>
      <Head>
        <title>oh god pls work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <BG_Finder2 game="1" onChange={IDupdate}></BG_Finder2>
        </div>
        {ID1 != 'start' ? <BG_display id = {ID1} game='1'></BG_display>:null}
        {ID1 != 'start'?<BG_Finder2 game="1" onChange={IDupdate}></BG_Finder2>:null}
        {ID1 != 'start'? <BG_display id = {ID2} game='2'></BG_display>:null}
      </main>

      <footer className='footer'>
        <p>Powered by dreams, BGG, and BoardGamePrices</p>
      </footer>
    </div>
  )
}


/*
THE CLIPBOARD


*/